from selenium.webdriver.common.by import By

class SignupLocators:
    name_field = (By.XPATH, "//div[@class='signup-form']//form//input[@name='name']")
    email_field = (By.XPATH, "//div[@class='signup-form']//form//input[@name='email']")
    signup_button = (By.XPATH, "//div[@class='signup-form']//form//button[text()='Signup']")
    user_exists_msg = (By.XPATH, "//p[contains(text(),'Email Address already exist!')]")
    name_field_account = (By.XPATH, "//input[@id='name']")
    password_field_account = (By.XPATH, "//input[@id='password']")
    dob_day = (By.XPATH, "//select[@id='days']")
    dob_month = (By.XPATH, "//select[@id='months']")
    dob_year = (By.XPATH, "//select[@id='years']")
    acc_firstname = (By.XPATH, "//input[@id='first_name']")
    acc_lastname = (By.XPATH, "//input[@id='last_name']")
    acc_company = (By.XPATH, "//input[@id='company']")
    acc_address1 = (By.XPATH, "//input[@id='address1']")
    acc_address2 = (By.XPATH, "//input[@id='address2']")
    acc_country = (By.XPATH, "//select[@id='country']")
    acc_state = (By.XPATH, "//input[@id='state']")
    acc_city = (By.XPATH, "//input[@id='city']")
    acc_zipcode = (By.XPATH, "//input[@id='zipcode']")
    acc_mobile_num = (By.XPATH, "//input[@id='mobile_number']")
    gender_male = (By.XPATH, "//input[@id='id_gender1']")
    gender_female = (By.XPATH, "//input[@id='id_gender2']")
    submit_button = (By.XPATH, "//button[@data-qa='create-account']")
    acc_created_msg = (By.XPATH, "//h2[@data-qa='account-created']")